@startuml
autonumber

group Open Market
Bacen -[#green]-> Bacen: Is it 6:30 am?
Bacen -[#green]> IF: send STR_17\nto open market
end

group Create an Withdraw
IF -[#red]> Bacen: start withdraw\n(STR_0)
Bacen -[#blue]-> IF: send agreed response\n(STR_R1)
Bacen -[#blue]-> IF: send error response\n(STR_E)
end

group Receive a Deposit
Bacen -[#green]> IF: start deposit\n(STR_R2)
IF -[#red]-> IF: Is it a\nvalid deposit?
IF -[#red]> Bacen: send error message\n(STR_10)
Bacen -[#blue]-> IF: send agreed response\n(STR_10R1)
Bacen -[#blue]-> IF: send error response\n(STR_10E)
end

group Close Market
Bacen -[#green]-> Bacen: Is it 6:30 pm?
Bacen -[#green]> IF: send STR_15\nto close market
end
@enduml