@startuml
class Users {
    id: uuid
    name: string
    type: string
    tax_id: string
    created_at: timestamp
    last_update: timestamp
    is_active: boolean
}

Users "1..*" -- "0..1" Accounts
class Accounts {
    id: uuid
    user_id: Users.user_id
    ispb: string
    branch: string
    account_number: string
    type: string
    opening_date: timestamp
    created_at: timestamp
    last_update: timestamp
    is_active: boolean
}

Accounts "1..*" -- "0..1" Entries
class Entries {
    id: uuid
    key: string
    type: string
    reason: string
    account_id: uuid
    cid: hash
    created_at: timestamp
    last_update: timestamp
    is_active: boolean
    status: string
}

Entries "1..*" -- "0..1" Claims
class Claims {
    id: uuid
    type: string
    key: string
    key_type: string
    is_claimer: boolean
    is_donor: boolean
    is_internal: boolean
    claimer_acc_ispb: string
    claimer_acc_branch: string
    claimer_acc_numer: string
    claimer_acc_type: string
    claimer_acc_opening_date: timestamp
    claimer_type: string
    claimer_name: string
    claimer_tax_id: string
    created_at: timestamp
    last_update: timestamp
    resolution_date: timestamp
    conclusion_date: timestamp
}

Entries "1..*" -- "0..1" Infractions
class Infractions {}

Entries "1..*" -- "0..1" Refunds
class Refunds {}

class Vsync {}

Vsync "1..*" -- "0..1" Cid_file
Cid_file "1..*" -- "0..1" Entries
class Cid_file {}

Vsync "1..*" -- "0..1" Event_file
Event_file "1..*" -- "0..1" Entries
class Event_file {}

Badlist "1..*" -- "0..1" Users
class Badlist {}

@enduml